from pathlib import Path

# ------------------------------------------------------------------------------
def parse_sections(path: Path):
    section_name = ""
    sections: dict[str, list] = {"": []}

    lines = path.read_text().splitlines()
    for line in lines:
        line = line.strip()
        if not line: continue
        if line.startswith('[') and line.endswith(']'):
            section_name = line
            sections[section_name] = []
            continue
        sections[section_name].append(line)

    del sections[""]
    del sections["[SELECTION_QUERY]"]
    return sections


# ------------------------------------------------------------------------------
def main():
    data_prot = parse_sections(FOLDER_TABLES / "prot.chem")
    data_nucl = parse_sections(FOLDER_TABLES / "rna.chem")

    data_out = {
        section_name: data_prot[section_name] + data_nucl[section_name]
        for section_name in data_prot
    }

    str_out = "\n\n".join((
        ";;; automatically generated by scripts/dev/merge_smiffer_tables.py",
        "[SELECTION_QUERY]\nnot (name H*)",
        '\n'.join(
            f"{section_name}\n{'\n'.join(lines)}\n"
            for section_name, lines in data_out.items()
        )
    ))
    (FOLDER_TABLES / "macro.chem").write_text(str_out)


################################################################################
if __name__ == "__main__":
    FOLDER_TABLES = Path("volgrids/_data/smiffer_tables")
    main()


################################################################################
