from pathlib import Path

# ------------------------------------------------------------------------------
def main():
    known_configs = set()
    content = PATH_INI_CONFIG.read_text()

    lines = filter(
        lambda line: line and not line.startswith(";"),
        (l.strip() for l in content.splitlines())
    )
    for line in lines:
        name = line.split('=')[0].strip()
        known_configs.add(name)

    PATH_PY_OUT.write_text('\n'.join((
        "### Generated by scripts/dev/update_known_configs.py",
        "KNOWN_CONFIGS = {",
        *(f'    "{name}",' for name in sorted(known_configs)),
        "}",
    )))


################################################################################
if __name__ == "__main__":
    PATH_INI_CONFIG = Path("config_volgrids.ini")
    PATH_PY_OUT = Path("volgrids/_data/known_configs.py")
    main()


################################################################################
# python3 scripts/dev/update_known_configs.py
