from pathlib import Path

# ------------------------------------------------------------------------------
def main():
    known_configs = set()
    for path_init in PATHS_INIT:
        content = path_init.read_text()
        i0 = content.find("_keys_other")
        i1 = content.find("__config_keys__")

        lines = (l.strip() for l in content[i0:i1].splitlines())
        lines = [line for line in lines if line and not line.startswith("#")]

        for line in lines[1:]: # skip the first line with "_keys_other"
            name = line.split(':')[0].strip()
            known_configs.add(name)

    PATH_PY.write_text('\n'.join((
        "### Generated by scripts/dev/update_known_configs.py.",
        "KNOWN_CONFIGS = {",
        *(f'    "{name}",' for name in sorted(known_configs)),
        "}",
    )))


################################################################################
if __name__ == "__main__":
    ROOT = Path("volgrids")
    PATH_PY = ROOT / "_misc" / "known_configs.py"
    PATHS_INIT = [
        ROOT / "__init__.py",
        ROOT / "smiffer" / "__init__.py",
        ROOT / "smutils" / "__init__.py",
        ROOT / "vgtools" / "__init__.py",
        ROOT / "veins"   / "__init__.py",
    ]
    main()


################################################################################
# python3 scripts/dev/update_known_configs.py
