from pathlib import Path

MAX_COMMENT_CHARS = 5 # lines starting with a larger amount of comment chars are disregarded

# ------------------------------------------------------------------------------
def main():
    known_configs: dict[str, tuple[str, str]] = {} # config_name: (default_value, comments)
    content = PATH_INI_CONFIG.read_text()

    name: str = None
    comment: list[str] = []

    lines = (l.strip() for l in content.splitlines())
    for line in lines:
        if not line: continue

        idx = line.find(';')
        pre_comment  = line[:idx].rstrip() if idx >= 0 else line
        post_comment = line[idx:] if idx >= 0 else ''

        post_comment_stripped = post_comment.lstrip(';')
        if len(post_comment) - len(post_comment_stripped) >= MAX_COMMENT_CHARS:
            continue

        if pre_comment: comment = []
        comment.append(
            post_comment_stripped.lstrip().replace("\"", "'")
        )
        if not pre_comment: continue

        name,value = pre_comment.split('=')
        known_configs[name.strip()] = (value.strip(), comment)


    known_configs = sorted(
        known_configs.items(), key = lambda t: t[0]
    )

    PATH_PY_OUT.write_text('\n'.join((
        "### Generated by scripts/dev/update_known_configs.py",
        "KNOWN_CONFIGS = {",
        *(
            f'    "{name}": ("{value}","{'\\n        '.join(comment)}"),'
            for name,(value,comment) in known_configs
        ),
        "}",
    )))


################################################################################
if __name__ == "__main__":
    PATH_INI_CONFIG = Path("config_volgrids.ini")
    PATH_PY_OUT = Path("volgrids/_data/known_configs.py")
    main()


################################################################################
# python3 scripts/dev/update_known_configs.py
